name: On Push Run

on: push

env:
  DEVOPS_DIR: michael

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: 
        pip install -r requirements.txt

    - name: Check-out devops repository
      uses: actions/checkout@v2
      with:
        repository: sanchomartin76/michael
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.DEVOPS_DIR }}

    - name: Hello World
      run: python ${{ env.DEVOPS_DIR }}/main.py
      shell: sh
