name: Build, test and lint

on:
  push:
    branches: [master, main]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.0' 
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run build
      
    
    # Run testing on the code
    - name: Run testing
